# Generated by Django 5.2.5 on 2025-09-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_class_student_teacher_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
