# Generated by Django 5.2.5 on 2025-09-05 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teacher_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='myapp.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.CharField(default='មិនកំណត់', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('គណិតវិទ្យា', 'គណិតវិទ្យា'), ('រូបវិទ្យា', 'រូបវិទ្យា'), ('គីមីវិទ្យា', 'គីមីវិទ្យា'), ('python', 'Python')], max_length=100),
        ),
    ]
