# Generated by Django 5.2.5 on 2025-09-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_class_students_alter_schedule_class_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tuition_fee',
        ),
        migrations.AddField(
            model_name='student',
            name='student_cunte',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
