# Generated by Django 4.1.3 on 2025-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_classroom_subject_remove_schedule_class_assigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classgood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_id', models.CharField(max_length=200, unique=True)),
                ('Teacher_name', models.CharField(max_length=200, null=True)),
                ('name_class', models.CharField(max_length=200)),
                ('student_cunte', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
