# Generated by Django 4.1.3 on 2025-09-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_classgood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorestudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
