# Generated by Django 4.1.3 on 2025-09-15 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_scorestudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorestudent',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='scorestudent',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='scorestudent',
            name='total_score',
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='AI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='Computer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='English',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='Khmer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='Math',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='Morality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='Physics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='chmisty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='python',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
            preserve_default=False,
        ),
    ]
