# Generated by Django 4.1.3 on 2025-09-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_scorestudent_average_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_cunte',
        ),
        migrations.AddField(
            model_name='student',
            name='student_majar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
