# Generated by Django 4.1.3 on 2025-09-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_student_student_cunte_student_student_majar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorestudent',
            name='student',
        ),
    ]
