# Generated by Django 4.1.3 on 2025-09-15 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_scorestudent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorestudent',
            name='classes',
            field=models.CharField(choices=[('ថ្នាក់ទី12A', 'ថ្នាក់ទី12A'), ('ថ្នាក់ទី12B', 'ថ្នាក់ទី12B'), ('ថ្នាក់ទី12C', 'ថ្នាក់ទី12C'), ('ថ្នាក់ទី12D', 'ថ្នាក់ទី12D'), ('ថ្នាក់ទី11A', 'ថ្នាក់ទី11A'), ('ថ្នាក់ទី11B', 'ថ្នាក់ទី11B'), ('ថ្នាក់ទី11C', 'ថ្នាក់ទី11C'), ('ថ្នាក់ទី11D', 'ថ្នាក់ទី11D'), ('ថ្នាក់ទី10A', 'ថ្នាក់ទី10A'), ('ថ្នាក់ទី10B', 'ថ្នាក់ទី10B'), ('ថ្នាក់ទី10C', 'ថ្នាក់ទី10C'), ('ថ្នាក់ទី10D', 'ថ្នាក់ទី10D')], default='ថ្នាក់ទី12A', max_length=200),
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
            preserve_default=False,
        ),
    ]
